In [31]:
# Dataset:
x = [10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5]
y1 = [8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68]
y2 = [9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74]
y3 = [7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73]
x4 = [8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8]
y4 = [6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56, 7.91, 6.89]

# Calculate: 
# - mean, 
# - standard deviation, 
# - correlation coefficient (Pearson)
# - variance ?

In [32]:
import numpy as np

In [33]:
# Średnia

In [34]:
np.mean([10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5])

9.0

In [35]:
np.mean([8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68])

7.500909090909093

In [36]:
np.mean([9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74])

7.50090909090909

In [37]:
np.mean([7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73])

7.5

In [38]:
np.mean([8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8])

9.0

In [39]:
np.mean([6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56, 7.91, 6.89])

7.500909090909091

In [40]:
# Wariancja

In [41]:
print(np.var([10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5]))

10.0


In [42]:
print(np.var([8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68]))

3.7520628099173554


In [43]:
print(np.var([9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74]))

3.752390082644628


In [44]:
print(np.var([7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73]))

3.747836363636364


In [45]:
print(np.var([8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8]))

10.0


In [46]:
print(np.var([6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56, 7.91, 6.89]))

3.7484082644628103


In [47]:
# Odchylenie standardowe

In [49]:
print('Mean:', np.mean(x))
print('Standard Deviation:', np.std(x))

Mean: 9.0
Standard Deviation: 3.1622776601683795


In [50]:
print('Mean:', np.mean(y1))
print('Standard Deviation:', np.std(y2))

Mean: 7.500909090909093
Standard Deviation: 1.93710869148962


In [51]:
print('Mean:', np.mean(y2))
print('Standard Deviation:', np.std(y2))

Mean: 7.50090909090909
Standard Deviation: 1.93710869148962


In [52]:
print('Mean:', np.mean(y3))
print('Standard Deviation:', np.std(y3))

Mean: 7.5
Standard Deviation: 1.9359329439927313


In [53]:
print('Mean:', np.mean(x4))
print('Standard Deviation:', np.std(x4))

Mean: 9.0
Standard Deviation: 3.1622776601683795


In [54]:
print('Mean:', np.mean(y4))
print('Standard Deviation:', np.std(y4))

Mean: 7.500909090909091
Standard Deviation: 1.9360806451340837


In [ ]:
# Korelacja

In [57]:
korelacja = np.corrcoef(x, y1)

print(korelacja)

[[1.         0.81642052]
 [0.81642052 1.        ]]


In [58]:
korelacja = np.corrcoef(x, y2)

print(korelacja)

[[1.         0.81623651]
 [0.81623651 1.        ]]


In [59]:
korelacja = np.corrcoef(x, y2)

print(korelacja)

[[1.         0.81623651]
 [0.81623651 1.        ]]


In [60]:
korelacja = np.corrcoef(x, y3)

print(korelacja)

[[1.         0.81628674]
 [0.81628674 1.        ]]


In [61]:
korelacja = np.corrcoef(x, y4)

print(korelacja)

[[ 1.         -0.31404671]
 [-0.31404671  1.        ]]


In [62]:
korelacja = np.corrcoef(x, x4)

print(korelacja)

[[ 1.  -0.5]
 [-0.5  1. ]]
